<a href="https://colab.research.google.com/github/TYamashita-22016/Math/blob/main/c2-2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import numpy as np
import numpy.random as random
import scipy as sp
import pandas as pd
from pandas import Series, DataFrame

import matplotlib.pyplot as ply
import matplotlib as mpl
import seaborn as sns
%matplotlib inline

%precision 3

data = np.array([9,2,3,4,10,6,7,8,1,5])
print(data)

print('データの型:', data.dtype)
print('次元数:', data.ndim)
print('要素数:', data.size)

print('掛け算', np.array([1,2,3,4,5,6,7,8,9,10]) * np.array([10,9,8,7,6,5,4,3,2,1,]))
print('累乗', np.array([1,2,3,4,5,6,7,8,9,10]) ** 2)
print('割り算', np.array([1,2,3,4,5,6,7,8,9,10]) / np.array([10,9,8,7,6,5,4,3,2,1,]))

print('そのまま：', data)
data.sort()
print('ソート後：', data)
data[::-1].sort()
print('降　順　：',data)
print('Min:', data.min())
print('Max:', data.max())
print('Sum:', data.sum())
print('Cum:', data.cumsum())
print('Ratio:', data.cumsum()/data.sum())

random.seed(129)
rnd_data=random.randn(10)
print('乱数10個の配列', rnd_data)

#ランダム抽出
print(random.choice(data,10))
print(random.choice(data,10,replace=False))



[ 9  2  3  4 10  6  7  8  1  5]
データの型: int64
次元数: 1
要素数: 10
掛け算 [10 18 24 28 30 30 28 24 18 10]
累乗 [  1   4   9  16  25  36  49  64  81 100]
割り算 [ 0.1    0.222  0.375  0.571  0.833  1.2    1.75   2.667  4.5   10.   ]
そのまま： [ 9  2  3  4 10  6  7  8  1  5]
ソート後： [ 1  2  3  4  5  6  7  8  9 10]
降　順　： [10  9  8  7  6  5  4  3  2  1]
Min: 1
Max: 10
Sum: 55
Cum: [10 19 27 34 40 45 49 52 54 55]
Ratio: [0.182 0.345 0.491 0.618 0.727 0.818 0.891 0.945 0.982 1.   ]
乱数10個の配列 [-1.629  0.496 -0.763  0.193  0.016  0.462 -0.264 -1.183 -0.633 -0.533]
[ 6  8 10  2 10  8  2 10  5  7]
[ 5  3  2  8  4  6  1  9  7 10]
