<a href="https://colab.research.google.com/github/TYamashita-22016/Math/blob/main/c2-3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
import numpy as np
import numpy.random as random
import scipy as sp
import pandas as pd
from pandas import Series, DataFrame

import matplotlib.pyplot as ply
import matplotlib as mpl
import seaborn as sns

import scipy.linalg as linalg
from scipy.optimize import minimize_scalar
from scipy.optimize import newton
%matplotlib inline

%precision 3

matrix = np.array([[1,-1,-1],[-1,1,-1],[-1,-1,1]])
#行列式の計算
print('行列式')
print(linalg.det(matrix))
#逆行列
print('逆行列')
print(linalg.inv(matrix))
#検算
print(matrix.dot(linalg.inv(matrix)))

eig_value, eig_vector = linalg.eig(matrix)
print('固有値')
print(eig_value)
print('固有ベクトル')
print(eig_vector)

def my_function(x):
  return(x**2+2*x+1)
print(newton(my_function,0))
print(minimize_scalar(my_function,method='Brent'))

行列式
-4.0
逆行列
[[ 0.  -0.5 -0.5]
 [-0.5 -0.  -0.5]
 [-0.5 -0.5  0. ]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
固有値
[-1.+0.j  2.+0.j  2.+0.j]
固有ベクトル
[[ 0.577  0.816  0.408]
 [ 0.577 -0.408 -0.816]
 [ 0.577 -0.408  0.408]]
-0.9999999852953906
     fun: 0.0
    nfev: 9
     nit: 4
 success: True
       x: -1.0000000000000002
