<a href="https://colab.research.google.com/github/TYamashita-22016/M_Math/blob/main/c5_2_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from numpy.ma.core import cumsum
import numpy as np
import numpy.random as random
import scipy as sp
import pandas as pd
from pandas import Series, DataFrame

import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
sns.set()
%matplotlib inline
%precision 3

import requests, zipfile
from io import StringIO
import io

from sklearn import linear_model

In [4]:
cond_data=np.array([True, True, False, False, True])

print(cond_data)

print(np.unique(cond_data))

[ True  True False False  True]
[False  True]


In [5]:
sample_data=np.arange(10)
print('元のデータ：',sample_data)
print('すべての要素の平方根：',np.sqrt(sample_data))
print('すべての要素のネイぴあ指数関数：',np.exp(sample_data))

元のデータ： [0 1 2 3 4 5 6 7 8 9]
すべての要素の平方根： [0.    1.    1.414 1.732 2.    2.236 2.449 2.646 2.828 3.   ]
すべての要素のネイぴあ指数関数： [1.000e+00 2.718e+00 7.389e+00 2.009e+01 5.460e+01 1.484e+02 4.034e+02
 1.097e+03 2.981e+03 8.103e+03]


In [7]:
sample_multi_array_data1=np.arange(9).reshape(3,3)
print(sample_multi_array_data1)

print('最小値：',sample_multi_array_data1.min())
print('最大値：',sample_multi_array_data1.max())
print('平均値：',sample_multi_array_data1.mean())
print('合計値：',sample_multi_array_data1.sum())

print('行の合計：',sample_multi_array_data1.sum(axis=1))
print('列の合計：',sample_multi_array_data1.sum(axis=0))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
最小値： 0
最大値： 8
平均： 4.0
合計： 36
行の合計： [ 3 12 21]
列の合計： [ 9 12 15]


In [8]:
cond_data=np.array([True, True, False, False, True])
print('少なくともTrueが1つあるかどうか：', cond_data.any())
print('すべてTrueかどうか：', cond_data.all())

少なくともTrueが1つあるかどうか： True
すべてTrueかどうか： False


In [11]:
sample_multi_array_data1=np.arange(9).reshape(3,3)

print('5より大きい数字がいくつあるか：', (sample_multi_array_data1>5).sum())

5より大きい数字がいくつあるか： 3


In [12]:
sample_multi_array_data1=np.arange(9).reshape(3,3)

print('対角成分：',np.diag(sample_multi_array_data1))
print('対角成分の和：',np.trace(sample_multi_array_data1))

対角成分： [0 4 8]
対角成分の和： 12
