<a href="https://colab.research.google.com/github/TYamashita-22016/Math/blob/main/practice2-4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [47]:
import numpy as np
import numpy.random as random
import scipy as sp
import pandas as pd
from pandas import Series, DataFrame

import matplotlib.pyplot as ply
import matplotlib as mpl
import seaborn as sns

import scipy.linalg as linalg
from scipy.optimize import minimize_scalar
from scipy.optimize import newton
%matplotlib inline

%precision 3

#演習2-4
matrix = np.array([[1,2,3],[1,3,2],[3,1,2]])
print('行列式')
print(linalg.det(matrix))
#演習2-5
#逆行列
print('逆行列')
print(linalg.inv(matrix))
#固有値と固有ベクトル
eig_value, eig_vector = linalg.eig(matrix)
print('固有値')
print(eig_value)
print('固有ベクトル')
print(eig_vector)

def my_function(x):
  return(x**3 + 2*x + 1)
print(newton(my_function,0))

行列式
-12.0
逆行列
[[-0.333  0.083  0.417]
 [-0.333  0.583 -0.083]
 [ 0.667 -0.417 -0.083]]
固有値
[ 6.   +0.j -1.414+0.j  1.414+0.j]
固有ベクトル
[[-0.577 -0.722  0.16 ]
 [-0.577 -0.143 -0.811]
 [-0.577  0.677  0.563]]
-0.45339765151640365
